@echo off
REM Vibe Remote Harness Mistral - Git Initialization Script (Windows)
REM ISO 27001 Compliant

SETLOCAL EnableDelayedExpansion

ECHO ========================================================================
ECHO  Vibe Remote Harness Mistral - Git Initialization
ECHO ========================================================================
ECHO.

REM Check if git is available
WHERE git >nul 2>&1
IF %ERRORLEVEL% NEQ 0 (
    ECHO ERROR: Git is not installed or not in PATH
    ECHO Please install Git from https://git-scm.com/
    GOTO :EXIT_ERROR
)

ECHO [INFO] Git found in PATH
ECHO.

REM Get current directory
SET "PROJECT_DIR=%~dp0.."
CD /D "%PROJECT_DIR%"

ECHO [INFO] Project directory: %PROJECT_DIR%
ECHO.

REM Check if already a git repository
IF EXIST ".git\" (
    ECHO WARNING: This directory is already a Git repository
    ECHO.
    GOTO :CHECK_REMOTE
)

REM Initialize git repository
ECHO [STEP 1/5] Initializing Git repository...
 git init
IF %ERRORLEVEL% NEQ 0 (
    ECHO ERROR: Failed to initialize Git repository
    GOTO :EXIT_ERROR
)
ECHO [SUCCESS] Git repository initialized
ECHO.

REM Create .gitignore
ECHO [STEP 2/5] Creating .gitignore...
IF NOT EXIST ".gitignore" (
    TYPE NUL > ".gitignore"
)
ECHO [SUCCESS] .gitignore exists
ECHO.

REM Add files to git
ECHO [STEP 3/5] Adding files to Git...
 git add .
IF %ERRORLEVEL% NEQ 0 (
    ECHO ERROR: Failed to add files to Git
    GOTO :EXIT_ERROR
)
ECHO [SUCCESS] Files added to Git
ECHO.

REM First commit
ECHO [STEP 4/5] Creating first commit...
git commit -m "Initial commit: Vibe Remote Harness Mistral ISO 27001 compliant project

Project Structure:
- src/server: Express + WebSocket server with security controls
- src/client: HTML/JS interface
- docs: ISO 27001 documentation (SECURITY, COMPLIANCE, ARCHITECTURE, IMPROVEMENTS)
- config: Configuration files
- scripts: Utility scripts

Features:
- Real-time WebSocket communication
- Security: Input validation, rate limiting, logging
- ISO 27001: 62% compliance (58/93 controls)

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>"
IF %ERRORLEVEL% NEQ 0 (
    ECHO ERROR: Failed to create first commit
    GOTO :EXIT_ERROR
)
ECHO [SUCCESS] First commit created
ECHO.

REM Check for remote
:CHECK_REMOTE
ECHO [STEP 5/5] Checking for remote repository...
ECHO.
ECHO Do you want to add a remote repository?
ECHO 1. Yes, I want to add a remote now
ECHO 2. No, I'll do it later
ECHO.
SET /P CHOICE=Enter choice (1 or 2):

IF "%CHOICE%"=="1" (
    GOTO :ADD_REMOTE
) ELSE (
    GOTO :COMPLETE
)

:ADD_REMOTE
SET /P REMOTE_URL=Enter remote URL (e.g., https://github.com/your-username/vibe-remote-harness.git):
IF "%REMOTE_URL%"=="" (
    ECHO No URL provided, skipping remote addition
    GOTO :COMPLETE
)

git remote add origin "%REMOTE_URL%"
IF %ERRORLEVEL% NEQ 0 (
    ECHO ERROR: Failed to add remote
    GOTO :EXIT_ERROR
)

git branch -M main
IF %ERRORLEVEL% NEQ 0 (
    ECHO ERROR: Failed to rename branch to main
    GOTO :EXIT_ERROR
)

ECHO.
ECHO Do you want to push to the remote now?
ECHO 1. Yes, push to main
ECHO 2. No, I'll push later
ECHO.
SET /P PUSH_CHOICE=Enter choice (1 or 2):

IF "%PUSH_CHOICE%"=="1" (
    git push -u origin main
    IF %ERRORLEVEL% NEQ 0 (
        ECHO WARNING: Failed to push to remote. You may need to authenticate.
        ECHO Please run: git push -u origin main
    ) ELSE (
        ECHO [SUCCESS] Pushed to remote repository
    )
)

:COMPLETE
ECHO.
ECHO ========================================================================
ECHO  Git Initialization Complete!
ECHO ========================================================================
ECHO.
ECHO Next steps:
ECHO 1. Copy .env.example to .env and configure your settings
ECHO 2. Run 'npm install' to install dependencies
ECHO 3. Run 'npm start' to start the server
ECHO 4. Access the UI at http://localhost:3000
ECHO.
ECHO Security Reminder:
ECHO - Never commit .env files or files containing secrets
ECHO - Review and update security configurations before production
ECHO - See docs/SECURITY.md for security best practices
ECHO.
ECHO ========================================================================

GOTO :EOF

:EXIT_ERROR
ECHO.
ECHO ========================================================================
ECHO  Git Initialization Failed
ECHO ========================================================================
EXIT /B 1
